# Generated by Django 4.0.6 on 2022-08-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petpe', '0005_story_image_likes'),
        ('petpe', '0006_delete_mystory'),
    ]

    operations = [
    ]
