# Generated by Django 4.0.6 on 2022-08-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_username'),
        ('accounts', '0003_remove_user_first_name_remove_user_last_name_and_more'),
    ]

    operations = [
    ]
